/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.sample;

class AppTest {
  // @Test
  // void appHasAGreeting() {
  // MainVerticle classUnderTest = new MainVerticle();
  // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  // }
}
