/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.sample.vertx1;

import static org.junit.jupiter.api.Assertions.*;

import io.vertx.core.Vertx;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  @DisplayName("Check that the server has started")
  void checkServerHasStarted(Vertx vertx) {
    assertTrue(true);
  }
}
