/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.sample;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Promise;

public class MainVerticle extends AbstractVerticle {

  /**
   * vert.x start – Vert.xアプリケーションの開始関数
   *
   * @param startPromise Vert.x起動時に使用するPromiseオブジェクト
   */
  public void start(Promise<Void> startPromise) throws Exception {
    // デプロイオプションに設定を設定する
    final var options = new DeploymentOptions().setConfig(config());

    // System.setProperty("io.vertx.web.router.setup.lenient", "true");

    // ServiceVerticleをデプロイする
    final var main = vertx.deployVerticle(MainServiceVerticle.class, options);
    main.onSuccess(id -> {
      startPromise.complete();
    }).onFailure(th -> {
      startPromise.fail(th);
    });

    // // デプロイ完了時の処理
    // CompositeFuture.all(main)
    // .onSuccess(ar -> startPromise.complete()) // 成功した場合、Promiseを完了させる
    // .onFailure(th -> startPromise.fail(th)); // 失敗した場合、Promiseを失敗させる
  }
}
