/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package vertxcore

import spock.lang.Specification

class MainVerticleTest extends Specification {
    // def "application has a greeting"() {
    //     setup:
    //     def app = new MainVerticle()

    //     when:
    //     def result = app.greeting

    //     then:
    //     result != null
    // }
}
