/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    eclipse
    id("io.vertx.vertx-plugin") version "1.4.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}

val mainClass = "jp.co.sample.MainVerticle" // findProperty("mainClass")?.toString()
val vertxVersion = "4.5.0" // findProperty("vertxVersion")?.toString()
val junitVersion = "5.6.2" // findProperty("junitVersion")?.toString()
val slf4jVersion = "2.0.9" // findProperty("slf4jVersion")?.toString()
val logbackVersion = "1.4.11" //findProperty("logbackVersion")?.toString()

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:${junitVersion}")

    // This dependency is used by the application.
    implementation("io.vertx:vertx-web:${vertxVersion}")
    implementation("io.vertx:vertx-web-client:${vertxVersion}")
    implementation("io.vertx:vertx-config:${vertxVersion}")
    implementation("io.vertx:vertx-web-templ-thymeleaf:${vertxVersion}")
    implementation("io.vertx:vertx-web-templ-handlebars:${vertxVersion}")
    // implementation("io.vertx:vertx-codegen:${vertxVersion}")
    implementation("io.vertx:vertx-auth-oauth2:${vertxVersion}")
    // implementation("io.vertx:vertx-auth-jwt:${vertxVersion}")
    // implementation("io.vertx:vertx-auth-properties:${vertxVersion}")
    implementation("io.vertx:vertx-auth-common:${vertxVersion}")

    // logger
    implementation("org.slf4j:slf4j-api:${slf4jVersion}")
    implementation("ch.qos.logback:logback-core:${logbackVersion}")
    implementation("ch.qos.logback:logback-classic:${logbackVersion}")
}

vertx {
    mainVerticle = "${mainClass}"
    vertxVersion = "${vertxVersion}"
    config="config.json"
}

application {
    // Define the main class for the application.
    mainClass.set("${mainClass}")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
