/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.sample.vertx1;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.CompositeFuture;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Promise;

/** main. */
public class Main extends AbstractVerticle {

  /**
   * vert.x start – Vert.xアプリケーションの開始関数
   *
   * @param startPromise Vert.x起動時に使用するPromiseオブジェクト
   */
  @Override
  public void start(Promise<Void> startPromise) {

    // デプロイオプションに設定を設定する
    final DeploymentOptions options = new DeploymentOptions().setConfig(config());

    // MainServiceVerticleとClientServiceVerticleをデプロイする
    final var main = vertx.deployVerticle(MainServiceVerticle.class, options);
    final var client = vertx.deployVerticle(ApiServiceVerticle.class, options);

    // デプロイ完了時の処理
    CompositeFuture.all(main, client)
        .onSuccess(ar -> startPromise.complete()) // 成功した場合、Promiseを完了させる
        .onFailure(th -> startPromise.fail(th)); // 失敗した場合、Promiseを失敗させる
  }
}
